site_name: Satip Documentation
repo_url: https://github.com/Future-Energy-Associates/satellite_image_processing
repo_name: OCF/sat-image-processing

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
#     logo: img/logo
#   favicon: img/favicon
  custom_dir: docs/overrides
  features:
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - search.suggest
  palette:
    primary: black

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/OpenClimateFix
    - icon: fontawesome/brands/github
      link: https://github.com/openclimatefix
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/open-climate-fix/
      
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - footnotes
  - attr_list
  - pymdownx.snippets
  - pymdownx.highlight
  - pymdownx.superfences
  
plugins:
  - search
  - mkdocstrings
      
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
nav:
  - Home: index.md
  - User Guides:
    - Downloading from EUMETSAT: EUMETSAT Download Example.md
  - About:
    - Open Climate Fix: OCF.md
  - API:
    - EUMETSAT: API/eumetsat.md
    - Utilities: API/utils.md