name: create_envfile

on: [push]

jobs:
  create-envfile:
    runs-on: "ubuntu-latest"
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_user_key: ${{ secrets.USER_KEY }}"
        envkey_user_secret: ${{ secrets.USER_SECRET }}
        envkey_slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        envkey_slack_id: ${{ secrets.SLACK_ID }}
        file_name: .env
      
  conda_setup:
    runs-on: "ubuntu-latest"
    steps:
      - uses: conda-incubator/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          activate-environment: foo
      - name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: PowerShell Core
        shell: pwsh
        run: |
          conda info
          conda list 
