name: create_envfile

on: [push]

jobs:
  create-envfile:
    runs-on: ubuntu-18.04
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        user_key: ${{ secrets.USER_KEY }}"
        user_secret: ${{ secrets.USER_SECRET }}
        slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        slack_id: ${{ secrets.SLACK_ID }}
        file_name: .env
