name: run_tests

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Load env vars
      uses: c-py/action-dotenv-to-setenv@v1
      with:
        env-file: .env
      
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
        
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest tests/test_eumetsat.py
      
